version: "3.9"

volumes:
  flowdapt-data:

networks:
  flowdapt:

# Use if you mount a config file to the container
# configs:
#   flowdapt-config:
#     file: ~/.flowdapt/configs/flowdapt.yaml

services:
  # Flowdapt
  flowdapt:
    # To use the local tag, build locally via `task build` first
    image: flowdapt-nowcast-plugin:local
    pull_policy: never  # This is needed to ensure we aren't trying to pull instead of reusing the local image, remove if using a remote image
    restart: on-failure:3
    # Mount the config file to the container's config directory
    # configs:
    #   - source: flowdapt-config
    #     target: /data/configs/flowdapt.yaml
    # Set the size of the tmpfs to 1GB and mount it to the container's /dev/shm directory
    # for Ray to use as shared memory, otherwise it will default to the /tmp directory
    # and harm performance.
    # tmpfs:
    #   - /tmp:size=3G
    volumes:
      # Mount the data volume to the container's data directory
      - flowdapt-data:/data
      # OR
      # Mount the local data directory to the container
      # - ~/.flowdapt:/data
      # Mount the tmpfs to the container's /dev/shm directory
      # (THIS IS FOR RAY ONLY)
      # - type: tmpfs
      #   target: /dev/shm
    environment:
      # Normally the container will not read any config files and will
      # just use the default values. However if we have a config to use and we have mounted
      # the local data dir, or we have injected a docker config we can set the name here like so:
      # FLOWDAPT__CONFIG_FILE: flowdapt.yaml
      # Set to console for debugging purposes
      FLOWDAPT__LOGGING__FORMAT: console
      # When running in docker we need to set the host to
      # allow external connections from outside docker or
      # from other containers. Port defaults to 8080.
      FLOWDAPT__RPC__API__HOST: 0.0.0.0
      FLOWDAPT__RPC__API__PORT: 8080
      # If using Ray, set the dashboard host so it's accessible from outside the container.
      # If you are not using Ray then comment the following line out.
      # FLOWDAPT__SERVICES__COMPUTE__EXECUTOR__DASHBOARD_HOST: 0.0.0.0
      FLOWDAPT__SERVICES__COMPUTE__EXECUTOR__TARGET: flowdapt.compute.executor.local.LocalExecutor
    ports:
      # Expose the port you want to use for the API, defaults to 8080
      - "8080:8080"
      # Expose any dashboard ports if using an Executor that supports it
      # This port is for the Ray dashboard, if you aren't using Ray then
      # comment the following line out.
      # - "9969:9969"
    networks:
      - flowdapt